[package]
name = "asterism"
version = "0.1.0"
description = "An open-source, distraction-free Markdown studio"
authors = ["you"]
edition = "2021"

[lib]
name = "asterism_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
